language: python
python:
- 3.6
- 3.5
- 3.4
- 2.7
install: pip install -U tox-travis
script: tox
deploy:
  provider: pypi
  distributions: sdist bdist_wheel
  user: gdonchyts
  skip-existing: true
  password:
    secure: F7ybQioul5WQdY54B6U1LAHFk7qqRdGEGSTYU5SdoT8zxsS+A34p+XrYUcwscXRopGYYnQEWkRrDfKyZVLQ6cM0o31yh/E/aFT6ooZD2drbMsmm/AHmwUmu8US8fJKIKfFQyntMWL1BOd5VEbj4oNFRVWcpW7hniPk5R+MrR30Mm1t+5zZI0Nt3SnxT1PPNaEYWMrDWLODisDblb1MP40luZaIZ7apLMHBuz3gSjQvOKbo82Jtfh9jybuTV1LHFjkQEpiLlmvlNXAlqSYW9b9TCpnmCnqAmch1wN72ruQoRrEfpvGMbHH10Yux988HOz9Qebq7hYNC807TuzH9E1gpT9Qa39tBHeqt4LwXJeNJh4wHsygCirTb4U6dSdqpnx4ceEOI5PQw7/r2dGTvHd7ifm9238M42wsz4aWaqq1WIaCWczT5B74mb5UiDrwW8Z2M8QvA5QMKBijdVzshxhEu7nD+ggaAxVx2V97jVUxzDP3TNuVnk9c4cCubujgsUW97zqa2UzZWnf8TA6ztVFInIlkFgFGAk23BkqbBk2NLkUVCMhwMb6dFlYkNQaNLftzRB7KXxXZysW1ajV1eRkCi/10pEfGn0Wc+QZ3QWh5W//xQlcby0Y/lkhW7+c3hPSE1RsI/KEJ/k77FoNiU/zNG9oYsa3WWvs8+/UC7SALvg=
  on:
    tags: true
    repo: openearth/hydro-model-builder
    python: 3.6
